### ISSUE TITLE
Spacegap showing a large negative 24H New Supply

### ISSUE THREAD

**Issue by rjan90** [spacegap/spacegap.github.io#11]
It seems like the calculation on 24H New Supply is off. It is currently showing a negative 4mill 24-hour new token suppuy.
![Screenshot from 2021-04-16 10-40-50](https://user-images.githubusercontent.com/8628857/114998232-0b36dc00-9ea1-11eb-931b-0481f43787b6.png)

**Comment by nicola** [comment]
I will investigate, but it seems possible to have a decrease in total supply.

This means that Locked+Burn > New tokens production.

**Comment by rjan90** [comment]
Great! Yeah, I thought about that as well, but the difference just seemed a bit too high.
